[package]
name = "yat"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0.0"
log = "0.4.17"
pretty_env_logger = "0.4.0"
tokio = { version = "1.27.0", features = ["full"] }
youtube_chat = "0.1.4"
